import { Painting, ArtStyle } from './types';

export const STYLES: ArtStyle[] = [
  'All', 
  'Renaissance', 
  'Baroque', 
  'Rococo', 
  'Neoclassicism', 
  'Romanticism', 
  'Realism', 
  'Impressionism', 
  'Post-Impressionism', 
  'Symbolism', 
  'Expressionism',
  'Surrealism',
  'Pre-Raphaelite'
];

export const PAINTINGS: Painting[] = [
  {
    id: '1',
    title: 'Mona Lisa',
    artist: 'Leonardo da Vinci',
    year: '1503–1506',
    style: 'Renaissance',
    biography: 'Leonardo da Vinci (1452–1519) was an Italian polymath of the High Renaissance who was active as a painter, draughtsman, engineer, scientist, theorist, sculptor, and architect.',
    analysis: 'The Mona Lisa is likely the most famous painting in the world. It is considered an archetypal masterpiece of the Italian Renaissance.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/300px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg',
    colorPalette: ['#2C2922', '#6B5B45', '#958458', '#2D3528', '#111210'],
    technique: 'Sfumato: A technique of allowing tones and colors to shade gradually into one another, producing softened outlines or hazy forms.',
    details: 'Notice the lack of eyebrows, which was common in the era or due to over-cleaning. The background features a winding path and bridge, suggesting a connection between humanity and nature.'
  },
  {
    id: '2',
    title: 'The Starry Night',
    artist: 'Vincent van Gogh',
    year: '1889',
    style: 'Post-Impressionism',
    biography: 'Vincent Willem van Gogh (1853–1890) was a Dutch Post-Impressionist painter. In just over a decade, he created about 2,100 artworks.',
    analysis: 'The Starry Night describes the view from the east-facing window of his asylum room at Saint-Rémy-de-Provence.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1024px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/300px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg',
    colorPalette: ['#1C3053', '#395786', '#C7B855', '#E9E4A9', '#111723'],
    technique: 'Impasto: Paint is laid on an area of the surface in very thick layers, usually thick enough that the brush or painting-knife strokes are visible.',
    details: 'The cypress tree in the foreground represents mourning, while the swirling sky may represent the divine or the turbulence of his mind.'
  },
  {
    id: '3',
    title: 'The Night Watch',
    artist: 'Rembrandt van Rijn',
    year: '1642',
    style: 'Baroque',
    biography: 'Rembrandt (1606–1669) was a Dutch Golden Age painter. He is generally considered one of the greatest visual artists in the history of art.',
    analysis: 'Famous for its colossal size and dramatic use of light and shadow (tenebrism).',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Night_Watch_-_HD.jpg/1024px-The_Night_Watch_-_HD.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Night_Watch_-_HD.jpg/300px-The_Night_Watch_-_HD.jpg',
    colorPalette: ['#0D0B0A', '#4A3B2A', '#8C2B24', '#D9A668', '#F2E3C6'],
    technique: 'Chiaroscuro & Tenebrism: Strong contrasts between light and dark to create a sense of volume and drama.',
    details: 'The girl in the yellow dress is a mascot for the company; the chicken at her waist (with claws) represents the company\'s emblem (Klauwe).'
  },
  {
    id: '4',
    title: 'Girl with a Pearl Earring',
    artist: 'Johannes Vermeer',
    year: '1665',
    style: 'Baroque',
    biography: 'Johannes Vermeer (1632–1675) was a Dutch Baroque Period painter who specialized in domestic interior scenes of middle-class life.',
    analysis: 'A tronie, a study of the head and shoulders of a girl wearing an exotic dress.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/800px-1665_Girl_with_a_Pearl_Earring.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/300px-1665_Girl_with_a_Pearl_Earring.jpg',
    colorPalette: ['#191919', '#E5CEAE', '#D9A548', '#345878', '#F2F2F2'],
    technique: 'Camera Obscura Influence: Soft focus and distinct highlights (halations) suggest Vermeer may have used optical devices.',
    details: 'The "pearl" is likely polished tin or glass, painted with just two strokes of white paint: a bright highlight and a soft reflection.'
  },
  {
    id: '5',
    title: 'The Birth of Venus',
    artist: 'Sandro Botticelli',
    year: '1485–1486',
    style: 'Renaissance',
    biography: 'Sandro Botticelli (1445–1510) was an Italian painter of the Early Renaissance.',
    analysis: 'Depicts the goddess Venus arriving at the shore after her birth, emerging from the sea fully-grown.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1024px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/300px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg',
    colorPalette: ['#A0C6C9', '#E8DCC3', '#D68F6C', '#4F6851', '#C85A3F'],
    technique: 'Tempera on Canvas: Linear perspective is largely ignored for a more decorative, flat composition emphasizing line.',
    details: 'Venus\'s pose is based on the "Venus Pudica" (modest Venus) of classical antiquity. The floating flowers are pink roses with golden hearts.'
  },
  {
    id: '6',
    title: 'The Great Wave off Kanagawa',
    artist: 'Hokusai',
    year: '1831',
    style: 'Realism',
    biography: 'Katsushika Hokusai (1760–1849) was a Japanese artist, ukiyo-e painter and printmaker of the Edo period.',
    analysis: 'The most famous work of Japanese art in the world. It depicts an enormous wave threatening three boats off the coast of Sagami Bay.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Great_Wave_off_Kanagawa2.jpg/1024px-Great_Wave_off_Kanagawa2.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Great_Wave_off_Kanagawa2.jpg/300px-Great_Wave_off_Kanagawa2.jpg',
    colorPalette: ['#2B4B6F', '#E8E3D7', '#253548', '#8AA6BF'],
    technique: 'Woodblock Print: Created using multiple carved woodblocks, one for each color (Prussian Blue was a new import).',
    details: 'The mountain in the background is Mount Fuji. The wave\'s claws mimic foam but also suggest a dragon\'s talons.'
  },
  {
    id: '7',
    title: 'The Swing',
    artist: 'Jean-Honoré Fragonard',
    year: '1767',
    style: 'Rococo',
    biography: 'Jean-Honoré Fragonard was a French painter and printmaker whose late Rococo manner was distinguished by remarkable facility, exuberance, and hedonism.',
    analysis: 'Considered to be one of the masterpieces of the Rococo era, and is Fragonard\'s best known work.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/The_Swing_-_Fragonard_-_1767.jpg/800px-The_Swing_-_Fragonard_-_1767.jpg', 
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/The_Swing_-_Fragonard_-_1767.jpg/300px-The_Swing_-_Fragonard_-_1767.jpg',
    colorPalette: ['#5C7A58', '#E8C3C3', '#C4B49C', '#2F4B2A', '#8C9A86'],
    technique: 'Pastel Hues & Fluid Brushwork: The scene feels light and airy, characteristic of Rococo frivolity.',
    details: 'The woman on the swing flings her shoe toward the statue of Cupid, who holds a finger to his lips in silence.'
  },
  {
    id: '8',
    title: 'Wanderer above the Sea of Fog',
    artist: 'Caspar David Friedrich',
    year: '1818',
    style: 'Romanticism',
    biography: 'Caspar David Friedrich was a 19th-century German Romantic landscape painter.',
    analysis: 'A masterpiece of Romanticism depicting a figure gazing out on a landscape covered in fog.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_Sea_of_Fog_-_Google_Art_Project.jpg/800px-Caspar_David_Friedrich_-_Wanderer_above_the_Sea_of_Fog_-_Google_Art_Project.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_Sea_of_Fog_-_Google_Art_Project.jpg/300px-Caspar_David_Friedrich_-_Wanderer_above_the_Sea_of_Fog_-_Google_Art_Project.jpg',
    colorPalette: ['#8AA0AE', '#2F3C42', '#D9C8B4', '#171B1E'],
    technique: 'Rückenfigur: A compositional device where a figure is seen from the back, contemplating the view, inviting the viewer to share the experience.',
    details: 'The landscape is not a real place but a composite of sketches from the Elbe Sandstone Mountains.'
  },
  {
    id: '9',
    title: 'The Kiss',
    artist: 'Gustav Klimt',
    year: '1907–1908',
    style: 'Symbolism',
    biography: 'Gustav Klimt was an Austrian symbolist painter and one of the most prominent members of the Vienna Secession movement.',
    analysis: 'The highpoint of Klimt\'s "Golden Phase".',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg/800px-The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg/300px-The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg',
    colorPalette: ['#B88A00', '#F2D250', '#4A3B2A', '#5C8A45', '#9C3328'],
    technique: 'Gold Leaf: Klimt applied real gold leaf to the canvas to create a shimmering, mosaic-like effect reminiscent of Byzantine art.',
    details: 'The man\'s robe has rectangular (masculine) patterns, while the woman\'s has circular (feminine) patterns.'
  },
  {
    id: '10',
    title: 'American Gothic',
    artist: 'Grant Wood',
    year: '1930',
    style: 'Realism',
    biography: 'Grant Wood (1891–1942) was an American painter best known for his paintings depicting the rural American Midwest.',
    analysis: 'Depicts a farmer standing beside his daughter – often mistaken for his wife.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg/800px-Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg/300px-Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg',
    colorPalette: ['#2F3A45', '#8C7D64', '#1A1C1E', '#A69B88'],
    technique: 'Regionalism: A realist modern art movement that included paintings, murals, lithographs, and illustrations depicting realistic scenes of rural and small-town America.',
    details: 'The window in the background is a "Carpenter Gothic" style, which inspired the title of the painting.'
  },
  {
    id: '11',
    title: 'Liberty Leading the People',
    artist: 'Eugène Delacroix',
    year: '1830',
    style: 'Romanticism',
    biography: 'Eugène Delacroix was the leader of the French Romantic school.',
    analysis: 'Commemorating the July Revolution of 1830, personifying Liberty.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg/1024px-Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg/300px-Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg',
    colorPalette: ['#8C7A63', '#2B3A42', '#C4A484', '#8C3B3B'],
    technique: 'Loose Brushwork: Delacroix prioritized color and movement over precise line, influencing the Impressionists.',
    details: 'The boy wielding pistols is believed to be the inspiration for the character Gavroche in Victor Hugo\'s Les Misérables.'
  },
  {
    id: '12',
    title: 'The Scream',
    artist: 'Edvard Munch',
    year: '1893',
    style: 'Expressionism',
    biography: 'Edvard Munch was a Norwegian painter whose best known work, The Scream, has become an iconic image of world art.',
    analysis: 'Represents the universal anxiety of modern man.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73.5_cm%2C_National_Gallery_of_Norway.jpg/800px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73.5_cm%2C_National_Gallery_of_Norway.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73.5_cm%2C_National_Gallery_of_Norway.jpg/300px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73.5_cm%2C_National_Gallery_of_Norway.jpg',
    colorPalette: ['#D97D54', '#2B4259', '#8C3B3B', '#D9A668'],
    technique: 'Synesthesia: Munch used swirling lines and jarring colors to make the viewer "hear" the scream through visual means.',
    details: 'The sky turns "blood red," which Munch famously described in his diary as the moment he sensed an "infinite scream passing through nature."'
  },
  {
    id: '13',
    title: 'The Hay Wain',
    artist: 'John Constable',
    year: '1821',
    style: 'Romanticism',
    biography: 'John Constable was an English landscape painter in the Romantic tradition.',
    analysis: 'Depicts a rural scene on the River Stour between the English counties of Suffolk and Essex.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/The_Hay_Wain_%281821%29_-_John_Constable.jpg/1024px-The_Hay_Wain_%281821%29_-_John_Constable.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/The_Hay_Wain_%281821%29_-_John_Constable.jpg/300px-The_Hay_Wain_%281821%29_-_John_Constable.jpg',
    colorPalette: ['#5C6B50', '#8C9A86', '#C4B49C', '#4A5B6C'],
    technique: 'Broken Color: Constable applied white highlights (sometimes called "Constable\'s snow") to simulate the sparkle of light on water and leaves.',
    details: 'The wagon is actually standing still in the water to cool the horses\' legs and soak the wheels to prevent shrinking.'
  },
  {
    id: '14',
    title: 'Ophelia',
    artist: 'John Everett Millais',
    year: '1851–1852',
    style: 'Pre-Raphaelite',
    biography: 'Sir John Everett Millais was an English painter and illustrator who was one of the founders of the Pre-Raphaelite Brotherhood.',
    analysis: 'Depicts the character Ophelia from Shakespeare\'s Hamlet, singing before she drowns in a river.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg/1024px-John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg/300px-John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg',
    colorPalette: ['#2F4B2A', '#5C7A58', '#8C9A86', '#C4B49C', '#4A5B6C'],
    technique: 'En Plein Air Background: Millais painted the background outdoors over several months, then painted the figure in his studio.',
    details: 'The flowers are symbolic: poppies for death, daisies for innocence, and roses for youth. The model, Elizabeth Siddal, posed in a bathtub kept warm by candles.'
  },
  {
    id: '15',
    title: 'Composition VIII',
    artist: 'Wassily Kandinsky',
    year: '1923',
    style: 'Expressionism',
    biography: 'Wassily Kandinsky was a Russian painter and art theorist. He is credited with painting one of the first recognized purely abstract works.',
    analysis: 'A complex arrangement of geometric shapes, lines, and colors.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Vassily_Kandinsky%2C_1923_-_Composition_8.jpg/1024px-Vassily_Kandinsky%2C_1923_-_Composition_8.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Vassily_Kandinsky%2C_1923_-_Composition_8.jpg/300px-Vassily_Kandinsky%2C_1923_-_Composition_8.jpg',
    colorPalette: ['#D9A668', '#8C3B3B', '#2B4259', '#F2E3C6'],
    technique: 'Geometric Abstraction: Using circles, triangles, and lines to represent spiritual and emotional truths rather than physical reality.',
    details: 'The circle in the top left corner is a recurring motif in Kandinsky\'s work, representing a synthesis of the greatest oppositions.'
  },
  {
    id: '16',
    title: 'The Card Players',
    artist: 'Paul Cézanne',
    year: '1890-1892',
    style: 'Post-Impressionism',
    biography: 'Paul Cézanne was a French artist and Post-Impressionist painter whose work laid the foundations of the transition from the 19th-century conception of artistic endeavour to a new and radically different world of art in the 20th century.',
    analysis: 'One of a series of oil paintings by the French Post-Impressionist artist Paul Cézanne.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Paul_C%C3%A9zanne_-_The_Card_Players_-_Google_Art_Project.jpg/1024px-Paul_C%C3%A9zanne_-_The_Card_Players_-_Google_Art_Project.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Paul_C%C3%A9zanne_-_The_Card_Players_-_Google_Art_Project.jpg/300px-Paul_C%C3%A9zanne_-_The_Card_Players_-_Google_Art_Project.jpg',
    colorPalette: ['#8C3B3B', '#4A3B2A', '#2B3A42', '#D9A668'],
    technique: 'Constructive Stroke: Cézanne used planes of color and small, repetitive brushstrokes that build up complex fields.',
    details: 'The bottle in the center acts as a dividing line between the two players, emphasizing the tension of the game.'
  },
  {
    id: '17',
    title: 'The Raft of the Medusa',
    artist: 'Théodore Géricault',
    year: '1818–1819',
    style: 'Romanticism',
    biography: 'Théodore Géricault was an influential French painter and lithographer. Although he died young, he was one of the pioneers of the Romantic movement.',
    analysis: 'Depicts a moment from the aftermath of the wreck of the French naval frigate Méduse.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg/1024px-JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg/300px-JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg',
    colorPalette: ['#4A3B2A', '#8C2B24', '#D9C8B4', '#171B1E'],
    technique: 'Pyramidal Composition: Two pyramids organize the figures: one of hope (the signaling group) and one of despair (the dead).',
    details: 'Géricault interviewed survivors and visited the morgue to study the color and texture of dying flesh.'
  },
  {
    id: '18',
    title: 'Nighthawks',
    artist: 'Edward Hopper',
    year: '1942',
    style: 'Realism',
    biography: 'Edward Hopper was a prominent American realist painter and printmaker.',
    analysis: 'Portrays people in a downtown diner late at night as viewed through the diner\'s large glass window.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Nighthawks_by_Edward_Hopper_1942.jpg/1024px-Nighthawks_by_Edward_Hopper_1942.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Nighthawks_by_Edward_Hopper_1942.jpg/300px-Nighthawks_by_Edward_Hopper_1942.jpg',
    colorPalette: ['#1A2B3C', '#2F4B2A', '#8C9A86', '#C4B49C'],
    technique: 'Cinematic Lighting: The use of artificial light creates deep shadows and a sense of isolation and silence.',
    details: 'There is no door to enter or exit the diner visible in the painting, enhancing the feeling of entrapment.'
  },
  {
    id: '19',
    title: 'The Two Fridas',
    artist: 'Frida Kahlo',
    year: '1939',
    style: 'Surrealism',
    biography: 'Frida Kahlo was a Mexican painter known for her many portraits, self-portraits, and works inspired by the nature and artifacts of Mexico.',
    analysis: 'A double self-portrait painted during her divorce from Diego Rivera.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/The_Two_Fridas.jpg/800px-The_Two_Fridas.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/The_Two_Fridas.jpg/300px-The_Two_Fridas.jpg',
    colorPalette: ['#2F4B2A', '#8C3B3B', '#D9A668', '#C4B49C'],
    technique: 'Symbolic Autobiography: Combining realistic portraiture with surreal/symbolic elements (exposed hearts, surgical clamps).',
    details: 'The Frida on the right holds a small amulet with a portrait of Diego Rivera; the vein connecting them is cut by the other Frida.'
  },
  {
    id: '20',
    title: 'Whistler\'s Mother',
    artist: 'James McNeill Whistler',
    year: '1871',
    style: 'Realism',
    biography: 'James Abbott McNeill Whistler was an American artist active during the American Gilded Age and based primarily in the United Kingdom.',
    analysis: 'Arrangement in Grey and Black No. 1.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Whistlers_Mother_high_res.jpg/1024px-Whistlers_Mother_high_res.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Whistlers_Mother_high_res.jpg/300px-Whistlers_Mother_high_res.jpg',
    colorPalette: ['#1C1C1C', '#4A4A4A', '#8C8C8C', '#D9D9D9'],
    technique: 'Tonalism: Emphasizing the arrangement of colors and tones over the narrative subject matter.',
    details: 'The painting on the wall is an etching by Whistler himself, "Black Lion Wharf".'
  },
  {
    id: '21',
    title: 'Grande Odalisque',
    artist: 'Jean-Auguste-Dominique Ingres',
    year: '1814',
    style: 'Neoclassicism',
    biography: 'Jean-Auguste-Dominique Ingres was a French Neoclassical painter.',
    analysis: 'Depicts an odalisque, or concubine.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Jean_Auguste_Dominique_Ingres_-_La_Grande_Odalisque_-_Google_Art_Project.jpg/1024px-Jean_Auguste_Dominique_Ingres_-_La_Grande_Odalisque_-_Google_Art_Project.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Jean_Auguste_Dominique_Ingres_-_La_Grande_Odalisque_-_Google_Art_Project.jpg/300px-Jean_Auguste_Dominique_Ingres_-_La_Grande_Odalisque_-_Google_Art_Project.jpg',
    colorPalette: ['#D9A668', '#2B4259', '#8C3B3B', '#F2E3C6'],
    technique: 'Mannerist Distortion: Ingres elongated the spine (by about 5 vertebrae) to increase the sensuality and elegance of the line.',
    details: 'The texture of the silk curtains and the peacock feather fan contrast with the smooth skin of the figure.'
  },
  {
    id: '22',
    title: 'The Garden of Earthly Delights',
    artist: 'Hieronymus Bosch',
    year: '1490–1510',
    style: 'Renaissance',
    biography: 'Hieronymus Bosch was a Dutch/Netherlandish painter known for fantastic illustrations.',
    analysis: 'A triptych depicting the history of mankind from creation to hell.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/El_jard%C3%ADn_de_las_Delicias%2C_de_El_Bosco.jpg/1024px-El_jard%C3%ADn_de_las_Delicias%2C_de_El_Bosco.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/El_jard%C3%ADn_de_las_Delicias%2C_de_El_Bosco.jpg/300px-El_jard%C3%ADn_de_las_Delicias%2C_de_El_Bosco.jpg',
    colorPalette: ['#5C7A58', '#D9A668', '#8C3B3B', '#C4B49C'],
    technique: 'Alla Prima Details: Despite the complexity, many small figures are painted directly without extensive underdrawing.',
    details: 'In the "Hell" panel, there is a pair of ears holding a knife, and a bird-monster devouring humans.'
  },
  {
    id: '23',
    title: 'Flaming June',
    artist: 'Frederic Leighton',
    year: '1895',
    style: 'Neoclassicism',
    biography: 'Sir Frederic Leighton was an English painter and sculptor.',
    analysis: 'Widely considered to be Leighton\'s magnum opus.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Frederic_Lord_Leighton_-_Flaming_June_-_Google_Art_Project.jpg/800px-Frederic_Lord_Leighton_-_Flaming_June_-_Google_Art_Project.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Frederic_Lord_Leighton_-_Flaming_June_-_Google_Art_Project.jpg/300px-Frederic_Lord_Leighton_-_Flaming_June_-_Google_Art_Project.jpg',
    colorPalette: ['#D97D54', '#E8DCC3', '#D68F6C', '#8C3B3B'],
    technique: 'Glazing: Layering thin, transparent coats of orange and gold paint to create the intense, glowing heat of the fabric.',
    details: 'The poisonous oleander branch in the top right corner suggests the link between sleep and death.'
  },
  {
    id: '24',
    title: 'Las Meninas',
    artist: 'Diego Velázquez',
    year: '1656',
    style: 'Baroque',
    biography: 'Diego Velázquez was the leading artist in the court of King Philip IV.',
    analysis: 'Raises questions about reality and illusion.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg/800px-Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg/300px-Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg',
    colorPalette: ['#1C1C1C', '#4A3B2A', '#D9A668', '#8C2B24'],
    technique: 'Loose Brushstrokes: Up close, the figures dissolve into blobs of paint; from a distance, they coalesce into photorealistic forms.',
    details: 'The mirror in the background reflects the King and Queen, placing them (or the viewer) in the position of the subject being painted.'
  },
  {
    id: '25',
    title: 'A Sunday on La Grande Jatte',
    artist: 'Georges Seurat',
    year: '1884',
    style: 'Post-Impressionism',
    biography: 'Georges Seurat was a French post-Impressionist artist.',
    analysis: 'The most famous example of pointillism.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/1024px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/300px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg',
    colorPalette: ['#5C7A58', '#2B4259', '#D9A668', '#8C3B3B'],
    technique: 'Pointillism: Applying small dots of pure color that blend in the viewer\'s eye (optical mixing) rather than on the palette.',
    details: 'Among the bourgeois crowd, there is a pet monkey on a leash, symbolizing the eccentricity and perhaps vice of modern life.'
  },
  {
    id: '26',
    title: 'The Lady of Shalott',
    artist: 'John William Waterhouse',
    year: '1888',
    style: 'Pre-Raphaelite',
    biography: 'John William Waterhouse was known for working in the Pre-Raphaelite style.',
    analysis: 'Representation of the ending of Alfred, Lord Tennyson\'s 1832 poem of the same name.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/John_William_Waterhouse_-_The_Lady_of_Shalott_-_Google_Art_Project.jpg/1024px-John_William_Waterhouse_-_The_Lady_of_Shalott_-_Google_Art_Project.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/John_William_Waterhouse_-_The_Lady_of_Shalott_-_Google_Art_Project.jpg/300px-John_William_Waterhouse_-_The_Lady_of_Shalott_-_Google_Art_Project.jpg',
    colorPalette: ['#2F4B2A', '#5C7A58', '#D9A668', '#C4B49C'],
    technique: 'Realistic Detail with Romantic Mood: Precise rendering of foliage combined with a dreamy, melancholic atmosphere.',
    details: 'The three candles at the front of the boat symbolize life; two have blown out, signifying her imminent death.'
  },
  {
    id: '27',
    title: 'Cafe Terrace at Night',
    artist: 'Vincent van Gogh',
    year: '1888',
    style: 'Post-Impressionism',
    biography: 'Vincent van Gogh was a Dutch Post-Impressionist painter.',
    analysis: 'Depicts the terrace of a café in Arles.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Vincent_Willem_van_Gogh_-_Cafe_Terrace_ at_Night_-_Google_Art_Project.jpg/800px-Vincent_Willem_van_Gogh_-_Cafe_Terrace_ at_Night_-_Google_Art_Project.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Vincent_Willem_van_Gogh_-_Cafe_Terrace_ at_Night_-_Google_Art_Project.jpg/300px-Vincent_Willem_van_Gogh_-_Cafe_Terrace_ at_Night_-_Google_Art_Project.jpg',
    colorPalette: ['#1C3053', '#F2D250', '#D9A668', '#2B3A42'],
    technique: 'Complementary Colors: Van Gogh used blue and orange (opposites on the color wheel) to make the lights "pop" against the night.',
    details: 'Though it is a night scene, Van Gogh famously used no black paint, only beautiful blues, violets, and greens.'
  },
  {
    id: '28',
    title: 'The Sleeping Gypsy',
    artist: 'Henri Rousseau',
    year: '1897',
    style: 'Post-Impressionism', // Naive Art / Primitivism
    biography: 'Henri Rousseau was a French post-impressionist painter in the Naïve or Primitive manner.',
    analysis: 'A fantastical depiction of a lion musing over a sleeping woman.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/La_Boh%C3%A9mienne_endormie.jpg/1024px-La_Boh%C3%A9mienne_endormie.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/La_Boh%C3%A9mienne_endormie.jpg/300px-La_Boh%C3%A9mienne_endormie.jpg',
    colorPalette: ['#1A2B3C', '#D9C8B4', '#8C3B3B', '#4A5B6C'],
    technique: 'Flatness and Outline: Rousseau lacked formal training, leading to a style with hard edges and a lack of traditional perspective, which influenced modernists.',
    details: 'The mandolin and jar imply the gypsy is a musician and traveler; the lion\'s tail is raised but stiff, adding to the dreamlike tension.'
  },
  {
    id: '29',
    title: 'Saturn Devouring His Son',
    artist: 'Francisco Goya',
    year: '1819–1823',
    style: 'Romanticism',
    biography: 'Francisco Goya was a Spanish romantic painter.',
    analysis: 'One of the "Black Paintings" painted directly onto the walls of his house.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/800px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/300px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg',
    colorPalette: ['#0D0B0A', '#4A3B2A', '#8C2B24', '#D9C8B4'],
    technique: 'Expressive Distortion: The anatomy is impossible and the brushwork frenzied, prioritizing raw horror over realism.',
    details: 'Saturn\'s eyes bulge white in madness; the body he eats is not a child but an adult, adding to the grotesque nature.'
  },
  {
    id: '30',
    title: 'The School of Athens',
    artist: 'Raphael',
    year: '1509–1511',
    style: 'Renaissance',
    biography: 'Raphael was an Italian painter and architect of the High Renaissance.',
    analysis: 'Represents all the greatest mathematicians, philosophers and scientists from classical antiquity.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/1024px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/300px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg',
    colorPalette: ['#D9A668', '#2B4259', '#8C3B3B', '#E8DCC3'],
    technique: 'Linear Perspective: The architecture converges at a single vanishing point between Plato and Aristotle, drawing the eye to the center.',
    details: 'Raphael included a portrait of Michelangelo (as Heraclitus) brooding in the foreground, and himself looking out from the far right.'
  }
];